### ISSUE TITLE
'Remember me'd user forgotten on restart

### ISSUE THREAD

**Issue by OJFord** [nicjo814/docker-plexmediaplayer#2]
It would be good if we could mark wherever's used for config as a volume, so that user login (and any other client settings) would persist across restarts.

**Comment by nicjo814** [comment]
It's been quite a while since I last looked at this image...
However I think it should be possible to map a local folder to where plex stores it's settings via the "-v" switch on commandline, I'm not sure where PMP stores it's settings though.

I'm not using the PMP software any more since I found out about the Plex plugin for Kodi. In my experience it gives the optimal combination with all of Kodi's settings and powerful video player together with the simplicity of Plex. For this purpose I've created another docker image called https://github.com/nicjo814/docker-kodi. It supports storing user settings via "-v \<local folder\>:/config:rw" on the commandline.

**Comment by nicjo814** [comment]
Just tested this and my settings persisted between container restarts. I guess you would like to map a folder into "/config" so it's persistent even if you remove the container and fire up a new one?

EDIT: Looks like all settings for PMP are stored in the /config folder within the container so I guess you should be able to pass "-v \<local folder\>:/config:rw" on commandline to make it persistent.
